import {
  Play,
  Square,
  GitBranch,
  Repeat,
  Type,
  Image,
  Volume2,
  Video,
  Clock,
  Timer,
  Keyboard,
  MousePointerClick,
  ListChecks,
  Database,
  Braces,
  Shuffle,
  FunctionSquare,
  Circle,
  Crosshair,
  Eraser,
  TextCursorInput,
  SlidersHorizontal,
  Variable,
  type LucideIcon,
} from "lucide-react";
import type { BlockCategory, BlockType } from "../../types/experiment";

export const categoryAccent: Record<BlockCategory, { text: string; bg: string; border: string }> = {
  flow: { text: "text-emerald-700", bg: "bg-emerald-50", border: "border-emerald-200" },
  stimulus: { text: "text-signal-dark", bg: "bg-signal-soft", border: "border-signal/25" },
  timing: { text: "text-violet-700", bg: "bg-violet-50", border: "border-violet-200" },
  response: { text: "text-orange-700", bg: "bg-orange-50", border: "border-orange-200" },
  data: { text: "text-teal-700", bg: "bg-teal-50", border: "border-teal-200" },
  randomization: { text: "text-pink-700", bg: "bg-pink-50", border: "border-pink-200" },
  functions: { text: "text-slate-700", bg: "bg-slate-100", border: "border-slate-300" },
};

export const blockIcons: Record<BlockType, LucideIcon> = {
  start: Play,
  end: Square,
  "if-else": GitBranch,
  loop: Repeat,
  "stimulus-text": Type,
  "stimulus-image": Image,
  "stimulus-audio": Volume2,
  "stimulus-video": Video,
  wait: Clock,
  timer: Timer,
  "keyboard-response": Keyboard,
  "mouse-response": MousePointerClick,
  "multiple-choice": ListChecks,
  "record-data": Database,
  variable: Braces,
  randomize: Shuffle,
  "custom-function": FunctionSquare,
  shape: Circle,
  fixation: Crosshair,
  "clear-screen": Eraser,
  "text-input": TextCursorInput,
  "slider-response": SlidersHorizontal,
  "set-variable": Variable,
};
